# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22']

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ matrix.node-version }}
    - name: Audit for vulnerabilities
      run: npm audit --audit-level=info --production
    - run: npm clean-install
    - run: npm audit signatures
    - run: npm run lint
    - run: npm run all
    - run: npm run test
    - name: 📊 Code coverage
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
      with:
        use_oidc: true
        disable_telem: true
    - name: Create SBOM step
      # see for usage: https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm
      run: npx @cyclonedx/cyclonedx-npm --help